### PR TITLE
Delagate creation of segmentPath/LoadSpec to DataSegmentPushers and add S3a support

### PR DESCRIPTION
**Pull request by b-slim**
- Delegation of creation/naming of segments to DataSegmentPusher
- Add Support of S3a schema
- Add dependency jars to Hdfs Module
- Update the hadoop compile version.

### CODE REVIEW

**Comment by b-slim** [comment]
This replaces https://github.com/druid-io/druid/pull/3940

**Comment by b-slim** [comment]
@akashdw can you take a look at this one as well.

**Comment by gianm** [comment]
@dclim could you please take a look?

File: api/src/main/java/io/druid/segment/loading/DataSegmentPusher.java [hunk 1]
```diff
@@ -19,15 +19,45 @@
...
 import io.druid.timeline.DataSegment;
 
 import java.io.File;
 import java.io.IOException;
+import java.net.URI;
+import java.util.Map;
 
 public interface DataSegmentPusher
 {
+  Joiner JOINER = Joiner.on("/").skipNulls();
```
Comment (nishantmonu51) [inline api/src/main/java/io/druid/segment/loading/DataSegmentPusher.java]: static final ?

File: extensions-core/hdfs-storage/src/main/java/io/druid/storage/hdfs/HdfsDataSegmentPusher.java [hunk 2]
```diff
@@ -198,4 +195,42 @@ public OutputStream openStream() throws IOException
...
     }
   }
+
+  @Override
+  public Map<String, Object> makeLoadSpec(URI finalIndexZipFilePath)
+  {
+    return  ImmutableMap.<String, Object>of("type", "hdfs", "path", finalIndexZipFilePath.toString());
+  }
+
+  private static final Joiner JOINER = Joiner.on("/").skipNulls();
```
Comment (nishantmonu51) [inline extensions-core/hdfs-storage/src/main/java/io/druid/storage/hdfs/HdfsDataSegmentPusher.java]: minor nit: reuse DataSegmentPusher.JOINER

File: extensions-core/hdfs-storage/src/main/java/io/druid/storage/hdfs/HdfsDataSegmentPusher.java [hunk 3]
```diff
@@ -115,15 +118,14 @@ public DataSegment push(File inDir, DataSegment segment) throws IOException
           storageDir,
           segment.getShardSpec().getPartitionNum()
```
Comment (akashdw) [inline extensions-core/hdfs-storage/src/main/java/io/druid/storage/hdfs/HdfsDataSegmentPusher.java]: `outIndexFile` could be created using `JobHelper.makeFileNamePath()`. And to do that, we can pull out the `makeFileNamePath()` method from `JobHelper` to `DataSegmentPusher`. Doing that will ensure no separate logic for index file path creation at 2 places.  
We can do the same for tmp file and `descriptor.json`.

File: extensions-core/hdfs-storage/src/main/java/io/druid/storage/hdfs/HdfsDataSegmentPusher.java [hunk 4]
```diff
@@ -115,15 +118,14 @@ public DataSegment push(File inDir, DataSegment segment) throws IOException
...
       ));
-
       final Path outDescriptorFile = new Path(String.format(
           "%s/%s/%d_descriptor.json",
           fullyQualifiedStorageDirectory,
           storageDir,
           segment.getShardSpec().getPartitionNum()
       ));
```
Comment (akashdw) [inline extensions-core/hdfs-storage/src/main/java/io/druid/storage/hdfs/HdfsDataSegmentPusher.java]: same as above.

File: indexing-hadoop/src/main/java/io/druid/indexer/JobHelper.java [hunk 5]
```diff
@@ -23,7 +23,6 @@
 import com.google.common.base.Predicate;
```
Comment (dclim) [inline indexing-hadoop/src/main/java/io/druid/indexer/JobHelper.java]: Line 718 of this file: should the URI be created with the scheme written in the loadSpec for the key 'S3Schema' if it exists? (and then default to s3n if it doesn't)

File: pom.xml [hunk 6]
```diff
@@ -71,7 +71,7 @@
         <netty.version>4.1.6.Final</netty.version>
         <slf4j.version>1.7.12</slf4j.version>
         <!-- If compiling with different hadoop version also modify default hadoop coordinates in TaskConfig.java -->
-        <hadoop.compile.version>2.3.0</hadoop.compile.version>
```
Comment (dclim) [inline pom.xml]: Did you encounter the exception: Exception in thread "main" java.lang.NoSuchMethodError: com.amazonaws.services.s3.transfer.TransferManagerConfiguration.setMultipartUploadThreshold(I)V

in your testing? There's some discussion on it here https://issues.apache.org/jira/browse/HADOOP-12420 and the conclusion at the end is that Hadoop 2.7.3 will only work with aws-java-sdk 1.7.4 until Hadoop 2.8 is released (https://issues.apache.org/jira/browse/HADOOP-12269). I was only able to get the s3a scheme working by downgrading Druid's version of aws-java-sdk to 1.7.4 so I'm curious what your experience was.

Comment (b-slim) [inline pom.xml]: @dclim i havn't run into this issue, maybe because i am not loading the s3a module, in fact i am using hdfs module to read segments.

File: api/src/main/java/io/druid/segment/loading/DataSegmentPusher.java (hunk 1 above)
Comment (b-slim) [inline api/src/main/java/io/druid/segment/loading/DataSegmentPusher.java]: it is by definition since it is part of interface

File: extensions-core/hdfs-storage/src/main/java/io/druid/storage/hdfs/HdfsDataSegmentPusher.java (hunk 2 above)
Comment (b-slim) [inline extensions-core/hdfs-storage/src/main/java/io/druid/storage/hdfs/HdfsDataSegmentPusher.java]: done

File: extensions-core/hdfs-storage/src/main/java/io/druid/storage/hdfs/HdfsDataSegmentPusher.java (hunk 3 above)
Comment (b-slim) [inline extensions-core/hdfs-storage/src/main/java/io/druid/storage/hdfs/HdfsDataSegmentPusher.java]: it is a good idea but this will require that druid-api has to depend on hadoop APIs which i am afraid it will trigger push back from no-hadoop-fan-club.. most of the logic is encapsulated at `dataSegmentPusher.makeIndexPathName` so i guess we are ok.

File: indexing-hadoop/src/main/java/io/druid/indexer/JobHelper.java (hunk 5 above)
Comment (b-slim) [inline indexing-hadoop/src/main/java/io/druid/indexer/JobHelper.java]: good catch done

File: pom.xml (hunk 6 above)
Comment (b-slim) [inline pom.xml]: @dclim 2.8 is released if that works for you i can update the dependency, please let me know.

File: extensions-core/hdfs-storage/src/main/java/io/druid/storage/hdfs/HdfsDataSegmentPusher.java (hunk 3 above)
Comment (akashdw) [inline extensions-core/hdfs-storage/src/main/java/io/druid/storage/hdfs/HdfsDataSegmentPusher.java]: 👍

File: pom.xml (hunk 6 above)
Comment (dclim) [inline pom.xml]: @b-slim nice! I don't have any concerns updating our client to 2.8

Comment (b-slim) [inline pom.xml]: done

**Comment by b-slim** [comment]
Timeout issue closing and opening.

**Comment by dclim** [comment]
👍 after Travis

**Comment by fjy** [comment]
@b-slim this is failing UT

**Comment by b-slim** [comment]
@dclim seems like there is a bunch of issue with the 2.8 it self, i am thinking about downgrading it to 2.7 again, what you think ?

**Comment by dclim** [comment]
@b-slim do you know what is causing the UT to fail? is it a configuration issue or something more fundamental?

downgrading to 2.7 seems reasonable to me if we don't have time to fix the issue, but I expect that people may then run into the aws java sdk incompatibility issue and we may need to walk them through downgrading from 1.10.x to 1.7.4

**Comment by dclim** [comment]
@b-slim have you tested this on a remote Hadoop cluster? I don't think it actually works as expected. The behavior I'm seeing is that even though the segments are getting pushed to S3, the loadSpec for the descriptor.json and in the druid_segments metadata table are showing type 'local' instead of 's3_zip' or 'hdfs'. 

This is happening because the loadSpec is now being generated by the DataSegmentPusher implementation which is being selected based on the value of `druid.storage.type`. However, the Druid properties are not being passed down into the system properties of the map/reduce JVMs and hence `druid.storage.type` does not get set and the default LocalDataSegmentPusher get used (even though the segments are actually written to S3 because the pusher isn't used for this in Hadoop jobs).

**Comment by b-slim** [comment]
@dclim i haven't tested that downstream yet, let me check it out and see how we can propagate those properties to the MM and hadoop JVM opts.

**Comment by dclim** [comment]
@b-slim cool, also take a look at #4180 - it might be a good idea to see if we can pass down the majority of the druid.* properties into the map and reduce JVMs to mitigate this class of issues - I was playing around with this earlier and ran into problems when I just blanket passed them all in (I think it was related to the extensions loadList probably due to the way we handle extensions in MR jobs) but I didn't investigate any further

**Comment by dclim** [comment]
@b-slim hey, just wondering how things are going with this PR

**Comment by b-slim** [comment]
So the issue with hadoop 2.8 is complex there is lot of class name/locations changes. i guess will stick with 2.7 and shade the libraries if needed maybe.

**Comment by dclim** [comment]
@b-slim that sounds good, let's stick with Hadoop 2.7. Have you had a chance to test this on an external Hadoop cluster? I think the last thing we need to do is push the Druid properties into the map/reduce JVMs, otherwise the loadSpec will always show 'local'

do you know if you'll have time to look at this for 0.10.1?

**Comment by b-slim** [comment]
@dclim sorry was underwater.. i have update the code checkout the last commit. Working on testing.

File: indexing-hadoop/src/main/java/io/druid/indexer/JobHelper.java [hunk 7]
```diff
@@ -308,6 +309,16 @@ public static void injectSystemProperties(Job job)
   {
     injectSystemProperties(job.getConfiguration());
   }
+  public static void injectDruidProprties(Configuration configuration) {
```
Comment (dclim) [inline indexing-hadoop/src/main/java/io/druid/indexer/JobHelper.java]: typo in 'properties'

File: indexing-hadoop/src/main/java/io/druid/indexer/JobHelper.java [hunk 8]
```diff
@@ -308,6 +309,16 @@ public static void injectSystemProperties(Job job)
...
+    String mapJavaOpst = configuration.get(MRJobConfig.MAP_JAVA_OPTS);
```
Comment (dclim) [inline indexing-hadoop/src/main/java/io/druid/indexer/JobHelper.java]: typo in 'opts'

File: indexing-hadoop/src/main/java/io/druid/indexer/JobHelper.java [hunk 9]
```diff
@@ -308,6 +309,16 @@ public static void injectSystemProperties(Job job)
...
+    String reduceJavaOpts = configuration.get(MRJobConfig.MAP_JAVA_OPTS);
+    for (String propName: System.getProperties().stringPropertyNames()){
+      if (propName.startsWith("druid.storage.")) {
```
Comment (dclim) [inline indexing-hadoop/src/main/java/io/druid/indexer/JobHelper.java]: In view of #4180 and similar, what do you think of making it configurable which props get passed down to the MR JVMs? Maybe similar to `druid.indexer.runner.allowedPrefixes`, have a `druid.indexer.hadoopProperties.allowedPrefixes` or similar and have `druid.storage.` always be an allowed prefix or be the default

**Comment by fjy** [comment]
@b-slim can we finish this up?

**Comment by b-slim** [comment]
@dclim can you check this out.

File: indexing-service/src/main/java/io/druid/indexing/common/config/TaskConfig.java [hunk 10]
```diff
@@ -31,7 +31,7 @@
 public class TaskConfig
 {
   public static final List<String> DEFAULT_DEFAULT_HADOOP_COORDINATES = ImmutableList.of(
-      "org.apache.hadoop:hadoop-client:2.3.0"
+      "org.apache.hadoop:hadoop-client:2.8.0"
```
Comment (dclim) [inline indexing-service/src/main/java/io/druid/indexing/common/config/TaskConfig.java]: 2.7.3

File: indexing-hadoop/src/main/java/io/druid/indexer/JobHelper.java [hunk 11]
```diff
@@ -309,6 +309,26 @@ public static void injectSystemProperties(Job job)
...
+  public static void injectDruidProperties(Configuration configuration, List<String> listOfAllowedPrefix) {
+    String mapJavaOpts = configuration.get(MRJobConfig.MAP_JAVA_OPTS);
+    String reduceJavaOpts = configuration.get(MRJobConfig.REDUCE_JAVA_OPTS);
+
+    for (String propName: System.getProperties().stringPropertyNames()){
+      for (String prefix : listOfAllowedPrefix) {
+        if (propName.startsWith(prefix)) {
+          mapJavaOpts = String.format("%s -D%s=%s", mapJavaOpts, propName, System.getProperty(propName));
+          reduceJavaOpts = String.format("%s -D%s=%s", reduceJavaOpts, propName, System.getProperty(propName));
+        }
```
Comment (dclim) [inline indexing-hadoop/src/main/java/io/druid/indexer/JobHelper.java]: Would be better to put a `break` in here if you get a match so that it doesn't add the same property multiple times if multiple prefixes match.

Comment (dclim) [inline indexing-hadoop/src/main/java/io/druid/indexer/JobHelper.java]: Also would be worth running a code style check, there's a few minor things I noticed

**Comment by dclim** [comment]
thanks @b-slim, just a few minor things

**Comment by b-slim** [comment]
@dclim thanks i have updated the PR tested it with HDFS but not S3 yet.

**Comment by b-slim** [comment]
@dclim this works fine with HDFS but to use i had to downgrade aws-sdk to 1.7.4.

**Comment by dclim** [comment]
@b-slim cool, yeah that was what I was seeing too

**Comment by leventov** [comment]
@b-slim TeamCity build failure could be ignored, or else https://github.com/druid-io/druid/pull/4348 should be merged first.

**Comment by b-slim** [comment]
@dclim actually this seems to be solved by [1.10.56](https://issues.apache.org/jira/browse/HADOOP-12420?focusedCommentId=15976997&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15976997) am giving it a try.

**Comment by b-slim** [comment]
@dclim this should work now thanks !

**Comment by dclim** [comment]
@b-slim awesome, thanks! 👍 after travis

**Comment by lonehacker** [comment]
Hi,
I discovered this issue while following the steps outline here - https://groups.google.com/forum/#!searchin/druid-user/Class$20org.apache.hadoop.fs.s3a.S3AFileSystem$20%7Csort:relevance/druid-user/efSrQt8a3S8/y8CsvraCBgAJ 
to access s3 buckets with v4 signature
Is there a better option than using master? Any easy way to downgrade aws-java-sdk?

**Comment by b-slim** [comment]
i dont think downgrading will work your best bet is to try this out by moving from s3n to s3a.

**Comment by lonehacker** [comment]
I'm facing the following issue - java.lang.NoSuchMethodError: com.amazonaws.services.s3.transfer.TransferManagerConfiguration.setMultipartUploadThreshold

Which is why I assumed it was a version mismatch problem.

Can you help on using s3a?

**Comment by lonehacker** [comment]
I just built master and tried this out with a remote hadoop cluster.
I'm getting the following error -
java.lang.NoSuchMethodError: com.amazonaws.services.s3.transfer.TransferManager.<init>
I checked that hadoop-aws and hadoop-client are the correct versions on middleManagers.
Is there any config change reqd to test out s3a?

**Comment by lonehacker** [comment]
@b-slim it doesn't seem like the 1.10.56 thing is working. I'll try with 1.7.4 tomorrow. if you have any pointers on how to make this work, please help.
Also, if you have tested this with s3a please do let me know

**Comment by b-slim** [comment]
@lonehacker can you share your job spec your indexer options and the logs i have run this internally with hadoop 2.7.3 and it works. i am suspecting  you have more than   1.10.56 jars in the classpath

**Comment by jon-wei** [comment]
@b-slim Have you been able to successfully run a batch ingestion task against Hadoop versions < 2.6.0 with this patch?

In my tests, I see the tasks succeed against hadoop clusters 2.6.0 and above but hit some classloader-related issues on versions under that

**Comment by b-slim** [comment]
@jon-wei i have run this with 2.7.3 (HDP 2.6) only.

**Comment by jon-wei** [comment]
@b-slim Can you try running with versions < 2.6.0 and see if there's a way to make that work? Otherwise that's a pretty big compatibility breakage

**Comment by b-slim** [comment]
@jon-wei thanks, can you please share the logs ? you think it is related to this patch ?

**Comment by jon-wei** [comment]
These are the errors I saw running against a sequenceiq 2.3.0 cluster, I tried various classloader options and got different errors:

With mapreduce.job.classloader = true

```
2017-06-07 20:01:52,673 INFO [main] org.apache.hadoop.mapreduce.v2.app.MRAppMaster: Created MRAppMaster for application appattempt_1496880055583_0001_000002
2017-06-07 20:01:52,778 WARN [main] org.apache.hadoop.conf.Configuration: job.xml:an attempt to override final parameter: mapreduce.job.end-notification.max.retry.interval;  Ignoring.
2017-06-07 20:01:52,782 WARN [main] org.apache.hadoop.conf.Configuration: job.xml:an attempt to override final parameter: mapreduce.job.end-notification.max.attempts;  Ignoring.
2017-06-07 20:01:52,785 INFO [main] org.apache.hadoop.mapreduce.v2.util.MRApps: Using job classloader
2017-06-07 20:01:52,860 FATAL [main] org.apache.hadoop.mapreduce.v2.app.MRAppMaster: Error starting MRAppMaster
java.lang.LinkageError: loader constraint violation: when resolving overridden method "org.apache.xerces.jaxp.DocumentBuilderImpl.newDocument()Lorg/w3c/dom/Document;" the class loader (instance of org/apache/hadoop/yarn/util/ApplicationClassLoader) of the current class, org/apache/xerces/jaxp/DocumentBuilderImpl, and its superclass loader (instance of <bootloader>), have different Class objects for the type org/w3c/dom/Document used in the signature
	at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.newDocumentBuilder(Unknown Source)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2210)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2172)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2089)
	at org.apache.hadoop.conf.Configuration.get(Configuration.java:838)
	at org.apache.hadoop.conf.Configuration.getTrimmed(Configuration.java:857)
	at org.apache.hadoop.conf.Configuration.getBoolean(Configuration.java:1255)
	at org.apache.hadoop.security.SecurityUtil.<clinit>(SecurityUtil.java:70)
	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:244)
	at org.apache.hadoop.security.UserGroupInformation.setConfiguration(UserGroupInformation.java:283)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.initAndStartAppMaster(MRAppMaster.java:1430)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.main(MRAppMaster.java:1386)
2017-06-07 20:01:52,863 INFO [main] org.apache.hadoop.util.ExitUtil: Exiting with status 1
```

----------------------

 With mapreduce.job.user.classpath.first = true

```
 2017-06-07T21:42:36,949 ERROR [main] org.apache.hadoop.mapreduce.v2.app.MRAppMaster - Error starting MRAppMaster
java.lang.NoSuchMethodError: org.apache.hadoop.http.HttpConfig.getSchemePrefix()Ljava/lang/String;
	at org.apache.hadoop.yarn.server.webproxy.amfilter.AmFilterInitializer.initFilter(AmFilterInitializer.java:41) ~[hadoop-yarn-server-web-proxy-2.3.0.jar:?]
	at org.apache.hadoop.http.HttpServer2.initializeWebServer(HttpServer2.java:400) ~[hadoop-common-2.7.3.jar:?]
	at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:351) ~[hadoop-common-2.7.3.jar:?]
	at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:114) ~[hadoop-common-2.7.3.jar:?]
	at org.apache.hadoop.http.HttpServer2$Builder.build(HttpServer2.java:290) ~[hadoop-common-2.7.3.jar:?]
	at org.apache.hadoop.yarn.webapp.WebApps$Builder.build(WebApps.java:261) ~[hadoop-yarn-common-2.7.3.jar:?]
	at org.apache.hadoop.yarn.webapp.WebApps$Builder.start(WebApps.java:303) ~[hadoop-yarn-common-2.7.3.jar:?]
	at org.apache.hadoop.mapreduce.v2.app.client.MRClientService.serviceStart(MRClientService.java:144) ~[hadoop-mapreduce-client-app-2.7.3.jar:?]
	at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193) ~[hadoop-common-2.7.3.jar:?]
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.serviceStart(MRAppMaster.java:1147) ~[hadoop-mapreduce-client-app-2.7.3.jar:?]
	at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193) ~[hadoop-common-2.7.3.jar:?]
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster$5.run(MRAppMaster.java:1552) ~[hadoop-mapreduce-client-app-2.7.3.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_121]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698) ~[hadoop-common-2.7.3.jar:?]
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.initAndStartAppMaster(MRAppMaster.java:1548) ~[hadoop-mapreduce-client-app-2.7.3.jar:?]
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.main(MRAppMaster.java:1481) [hadoop-mapreduce-client-app-2.7.3.jar:?]
2017-06-07T21:42:36,957 INFO [main] org.apache.hadoop.util.ExitUtil - Exiting with status 1
```

--------------------------

With neither
```
Error: com.google.inject.util.Types.collectionOf(Ljava/lang/reflect/Type;)Ljava/lang/reflect/ParameterizedType;
```

**Comment by jon-wei** [comment]
@b-slim If we can't get <2.6.0 hadoop working, I'm okay with dropping support for those older versions with the 0.10.2 release, but I think we should probably make a community decision, I'll start a druid-dev thread regarding that

**Comment by jon-wei** [comment]
Started a thread on dropping support for Hadoop <2.6.0 if needed:

https://groups.google.com/forum/#!topic/druid-development/vFjR0pdq83U

**Comment by b-slim** [comment]
@jon-wei  thanks looks like it is a long shot to make it work with less than 2.6, will give it a try.

**Comment by jon-wei** [comment]
@b-slim Can you add docs for the changes in this patch?

**Comment by dclim** [comment]
@b-slim @jon-wei somewhat related - since we're upgrading aws-java-sdk and will be testing the new version, I was thinking to bump it to a later version since 1.10.56 is already over a year old. Any objections to this?

**Comment by jon-wei** [comment]
@dclim I have no objection, but I think we can't upgrade to 1.11+ because Druid is still on Jackson 2.4:

https://github.com/druid-io/druid/pull/4313

That PR updated aws-java-sdk to 1.10.77 and also changed Druid to pull in aws-java-sdk-ec2 instead of aws-java-sdk

**Comment by dclim** [comment]
@jon-wei ah, thanks for pointing out that patch, that sounds good to me

**Comment by b-slim** [comment]
@jon-wei i will send a followup pr this week thanks !

**Comment by himanshug** [comment]
continuing....  https://github.com/druid-io/druid/pull/4313#issuecomment-309854006 and https://github.com/druid-io/druid/pull/4313#issuecomment-309873993
does anyone know what aws properties are needed to be set to what values in integration testing environment to fix the situation ?

**Comment by b-slim** [comment]
@himanshug setting the version  to `1.10.77` at the hdfs pom file will bring down the correct jar. If that works we can have a global aws-version as fix.

**Comment by gianm** [comment]
@himanshug @b-slim does that mean we need to change something for 0.10.1 (rc2)?

**Comment by himanshug** [comment]
@gianm most likely, yes... m gonna test https://github.com/himanshug/druid/commit/9632b0cb8fe9beb60d0a837af951238b5ffb1219

**Comment by moscowart** [comment]
Guys, I'm sorry but I still can't make `Hadoop 2.7.3` and `aws-java-sdk-s3:1.10.77` work with `s3a`. Here's what I have. Please tell me what I'm doing wrong. 

I'm using `Druid 0.10.1` and I use S3 as a deep storage. I put `hadoop-aws-2.7.3.jar` into `hadoop-dependencies/hadoop-client/2.7.3/`. Then I put `aws-java-sdk-s3-1.10.77.jar` in `lib/`. And here's my `core-site.xml`:
```
<configuration>
  <property>
    <name>fs.s3a.endpoint</name>
    <value>s3.eu-central-1.amazonaws.com</value>
  </property>

  <property>
    <name>fs.s3.impl</name>
    <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
  </property>

  <property>
    <name>fs.s3n.impl</name>
    <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
  </property>

  <property>
    <name>fs.s3n.awsAccessKeyId</name>
    <value>TRATATA</value>
  </property>

  <property>
    <name>fs.s3n.awsSecretAccessKey</name>
    <value>BLABLABLA</value>
  </property>
</configuration>
```

Still I have: `java.lang.NoSuchMethodError: com.amazonaws.services.s3.transfer.TransferManager.<init>(Lcom/amazonaws/services/s3/AmazonS3;Ljava/util/concurrent/ThreadPoolExecutor;)V`

File: extensions-core/s3-extensions/src/main/java/io/druid/storage/s3/S3DataSegmentPusherConfig.java [hunk 12]
```diff
@@ -39,6 +39,9 @@
   @JsonProperty
   @Min(0)
   private int maxListingLength = 1000;
+  // use s3n by default for backward compatibility
+  @JsonProperty
+  private boolean useS3aSchema = false;
```
Comment (Gauravshah) [inline extensions-core/s3-extensions/src/main/java/io/druid/storage/s3/S3DataSegmentPusherConfig.java]: can we add this to documentation ?

Comment (Gauravshah) [reply extensions-core/s3-extensions/src/main/java/io/druid/storage/s3/S3DataSegmentPusherConfig.java]: @dclim @b-slim

**Comment by samarthjain** [comment]
We are currently running into an issue where the hadoop-indexer job is making segment entries in the metadata store using the local load spec. As a result, segments are not getting loaded. The commentary here suggests we may need to pass 
druid.storage.type to the indexer job. How do we do this? Or better, has this issue been fixed in later releases?

**Comment by samarthjain** [comment]
Alternatively, is there a way to configure the DataSegmentPusher? Right now, by default, LocalDataSegmentPusher is injected. This issue is preventing us from using druid-10.1 for bulk ingestion.

**Comment by b-slim** [comment]
@samarthjain this not the best place to ask questions, you need to set druid.storage.type=hdfs or any other deep storage type as part of the properties file.

File: extensions-core/s3-extensions/src/main/java/io/druid/storage/s3/S3DataSegmentPusherConfig.java (hunk 12 above)
Comment (palanieppan-m) [reply extensions-core/s3-extensions/src/main/java/io/druid/storage/s3/S3DataSegmentPusherConfig.java]: We are using S3 as deep storage. The batch ingestion by default uses S3N uri - is this the configuration to set so that it uses S3A url format? If so where should this be set? In the deep storage config along with other properties? Is it druid.storage.useS3aSchema = true?

@b-slim

Comment (moscowart) [reply extensions-core/s3-extensions/src/main/java/io/druid/storage/s3/S3DataSegmentPusherConfig.java]: @palanieppan-m you have to add this to hadoop config file like `core-site.xml`. If you don't have any other configurations it would look something like:
```
<configuration>
  <property>
    <name>fs.s3a.endpoint</name>
    <value>s3.eu-central-1.amazonaws.com</value>
  </property>

  <property>
    <name>fs.s3.impl</name>
    <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
  </property>

  <property>
    <name>fs.s3n.impl</name>
    <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
  </property>

  <property>
    <name>fs.s3a.access.key</name>
    <value>${S3_ACCESS_KEY}</value>
  </property>

  <property>
    <name>fs.s3a.secret.key</name>
    <value>${S3_SECRET_KEY}</value>
  </property>
</configuration>
```

Don't forget to change endpoint if you're using different region.

Next create another config file named `jets3t.properties` with the following:
```
s3service.s3-endpoint = s3.eu-central-1.amazonaws.com

storage-service.request-signature-version=AWS4-HMAC-SHA256
```

Again change region if needed.

And lastly all this thing will only work with patched Hadoop libraries. I used Hadoop 2.7.3 from HDP 2.5.3 distribution. It is patched with aws-java-sdk-*:1.10.6 and works perfectly with it. So I replaced hadoop and aws jars and only then it worked. For more info you can take a look at this discussion: https://github.com/druid-io/druid/issues/4977

**Comment by palanieppan-m** [comment]
@moscowart, your proposal is workaround for the default behavior of Druid
which uses S3N URL scheme. To get that to work, you have to configure
Hadoop to support it.

In this PR though, it looks like behavior can be changed such that Druid
always S3A URL scheme instead, provided you turn on a config. I was
enquiring whether why understanding is correct and what's the config name
to turn on this behavior.

File: extensions-core/s3-extensions/src/main/java/io/druid/storage/s3/S3DataSegmentPusherConfig.java (hunk 12 above)
Comment (palanieppan-m) [reply extensions-core/s3-extensions/src/main/java/io/druid/storage/s3/S3DataSegmentPusherConfig.java]: @moscowart, your proposal is workaround for the default behavior of Druid which uses S3N URL scheme. To get that to work, you have to configure Hadoop to support it.

In this PR though, it looks like behavior can be changed such that Druid always S3A URL scheme instead, provided you turn on a config. I was enquiring whether why understanding is correct and what's the config name to turn on this behavior.
